NEI <- readRDS("summarySCC_PM25.rds")
s <- split(NEI, NEI$year)
totalEmission <- sapply(s, function(x) sum(x[,"Emissions"]))
totalEmission <- data.frame(names(totalEmission), c(totalEmission[[1]],totalEmission[[2]],totalEmission[[3]],totalEmission[[4]]))
names(totalEmission) <- c("Year","TotalEmissions")
barplot(totalEmission$TotalEmissions, names.arg=totalEmission$Year, xlab = "Year", ylab="Total Emissions (ton)")
title("Total emissions from PM2.5 vs Year")
dev.copy(png, file="plot1.png")
dev.off()